<?xml version="1.0" encoding="utf-8"?>
<!--
   Licensed to the Apache Software Foundation (ASF) under one or more
   contributor license agreements.  See the NOTICE file distributed with
   this work for additional information regarding copyright ownership.
   The ASF licenses this file to You under the Apache License, Version 2.0
   (the "License"); you may not use this file except in compliance with
   the License.  You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-->
<!DOCTYPE contributors
[
<!ELEMENT name (first?, middle?, last)>
<!ELEMENT contributors (introduction, name+)>
<!ELEMENT first (#PCDATA)>
<!ELEMENT introduction (#PCDATA)>
<!ELEMENT middle (#PCDATA)>
<!ELEMENT last (#PCDATA)>
]
>

<contributors>
  <introduction>
  These are some of the many people who have helped with this Ant Library.
  </introduction>
  <name>
    <first>Alexey</first>
    <last>Solofnenko</last>
  </name>
  <name>
    <first>Antoine</first>
    <last>Levy-Lambert</last>
  </name>
  <name>
    <first>Brian</first>
    <last>Watson</last>
  </name>
  <name>
    <first>Chris</first>
    <last>Nagy</last>
  </name>
  <name>
    <first>Conor</first>
    <last>MacNeill</last>
  </name>
  <name>
    <first>Dave</first>
    <last>Brosius</last>
  </name>
  <name>
    <first>Martijn</first>
    <last>Kruithof</last>
  </name>
  <name>
    <first>Mike Schilling</first>
    <last>Kruithof</last>
  </name>
  <name>
    <first>Peter</first>
    <last>Donald</last>
  </name>
  <name>
    <first>Peter</first>
    <last>Reilly</last>
  </name>
  <name>
    <first>Stefan</first>
    <last>Bodewig</last>
  </name>
  <name>
    <first>Stephane</first>
    <last>Bailliez</last>
  </name>
  <name>
    <first>Steve</first>
    <last>Loughran</last>
  </name>
</contributors>
